# Generated by Django 3.1.4 on 2021-01-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediator_name', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'Mediators',
            },
        ),
        migrations.CreateModel(
            name='MediatorEndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('mediator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mediator')),
            ],
            options={
                'db_table': 'MediatorEndPoints',
            },
        ),
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField()),
                ('path_type', models.CharField(choices=[('in_dir', 'Input Directory'), ('out_dir', 'Output Directory'), ('err_dir', 'Error Directory')], max_length=100)),
                ('mediator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mediator')),
            ],
            options={
                'db_table': 'FilePaths',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('mediator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mediator')),
            ],
            options={
                'db_table': 'Files',
            },
        ),
    ]
