# Generated by Django 3.1.4 on 2021-01-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediatorendpoint',
            old_name='endpoint',
            new_name='end_point',
        ),
    ]
