# Generated by Django 3.1.4 on 2021-01-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210108_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='filepath',
            name='path_type',
            field=models.CharField(choices=[('in_dir', 'Input Directory'), ('out_dir', 'Output Directory'), ('err_dir', 'Error Directory'), ('root_dir', 'Root Directory')], max_length=100),
        ),
    ]
