# Generated by Django 3.1.4 on 2021-01-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210108_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='end_point',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MediatorEndPoint',
        ),
    ]
