# Generated by Django 3.1.5 on 2021-01-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_filepath_path_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepath',
            old_name='file_path',
            new_name='directory_path',
        ),
    ]
